apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-a4d9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-a4d9"
  template:
    metadata:
      labels:
        app: "myaks-a4d9"
    spec:
      containers:
        - name: "myaks-a4d9"
          image: "myacrrrrr.azurecr.io/myaks"
          ports:
          - containerPort: 80