on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n myacrrrrr -g myacrrrrr9170-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n myacrrrrr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n myacrrrrr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n myacrrrrr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: myacrrrrr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AcrHelloworld" -f  "AcrHelloworld/Dockerfile" -t myacrrrrr.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=AcrHelloworld/Dockerfile
        docker push myacrrrrr.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksa551-acr | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksa551-acr`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksa551-acr
        container-registry-url: myacrrrrr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksa551-acr
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myacrrrrr.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth   
